# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=16)),
                ('position', models.CharField(max_length=16)),
                ('responsiblities', models.CharField(max_length=128)),
            ],
        ),
    ]
